
name: Push Check Pipeline

on: [push, pull_request]

jobs:
  build:
    name: Build & Lint Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn

      - name: Enforce code style
        run: yarn lint

      - name: Build without failing
        run: yarn build
